apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  CreateClusterAddress: "http://create-contact-svc:80"
  DeleteClusterAddress: "http://delete-contact-svc:80"
  UpdateClusterAddress: "http://update-contact-svc:80"
