apiVersion: v1
kind: Service
metadata:
  name: api-gateway-svc
  labels:
    app: contact-api
spec:
  selector:
    app: contact-api
    service: gateway
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000
