apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc
  labels:
    app: contact-api
    service: pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
