apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete-contact
  labels:
    app: contact-api
    service: delete
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-api
      service: delete
  template:
    metadata:
      labels:
        app: contact-api
        service: delete
    spec:
      containers:
        - name: delete-contact
          image: gricardo10/delete-contact-api:1.0.1
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: delete-contact-config
                  key: AppEnv
            - name: ConnectionStrings__Database
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: connectionString
            - name: ConnectionStrings__RabbitMq
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: connectionString
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"