apiVersion: v1
kind: Service
metadata:
  name: delete-contact-svc
  labels:
    app: contact-api
spec:
  selector:
    app: contact-api
    service: delete
  type: ClusterIP
  #type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      #nodePort: 31003

