apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s

    scrape_configs:
      - job_name: "api-gateway"
        metrics_path: /metrics
        static_configs:
          - targets:
              - "api-gateway-svc.default.svc.cluster.local:8080"

      - job_name: "create-contact-api"
        metrics_path: /metrics
        static_configs:
          - targets:
              - "create-contact-svc.default.svc.cluster.local:8080"

      - job_name: "delete-contact-api"
        metrics_path: /metrics
        static_configs:
          - targets:
              - "delete-contact-svc.default.svc.cluster.local:8080"

      - job_name: "update-contact-api"
        metrics_path: /metrics
        static_configs:
          - targets:
              - "update-contact-svc.default.svc.cluster.local:8080"

      - job_name: "rabbitmq"
        metrics_path: /metrics
        static_configs:
          - targets:
              - "rabbitmq-svc.default.svc.cluster.local:15692"
