apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
  labels:
    app: contact-api
spec:
  selector:
    app: rabbitmq
  type: NodePort
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 31671
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 31672
