{
 "title": "Contact Manager - Microservices",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "API Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_private_memory_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Total request by service",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (http_requests_received_total{endpoint!=\"/health\", instance!=\"api-gateway-svc.default.svc.cluster.local:8080\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average request latency by endpoint",
   "type": "bargauge",
   "description": "Tempo médio de resposta (latência)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (rate(http_request_duration_seconds_sum[5m])) / sum by(job) (rate(http_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Status Code Distribution",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(code) (http_requests_received_total{job=\"api-gateway\", code!=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput by endpoint",
   "type": "bargauge",
   "description": "número de requisições processadas por unidade de tempo",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (rate(http_requests_received_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage history",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "process_private_memory_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "CPU Usage history",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "{{job}}" }
   ]
  },
  { "title": "Alerts Manager", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 } }
 ]
}