apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  connectionString: "Server=mssql-svc;Database=ContactManagerDb;User Id=sa;Password=P@ssw0rd1;Encrypt=False;TrustServerCertificate=True"