apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  labels:
    app: contact-api
    service: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: contact-db-secret
                  key: SA_PASSWORD
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P P@ssw0rd1 -Q 'SELECT 1' -C"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          volumeMounts:
            - name: mssql-storage
              mountPath: /var/opt/mssql
      volumes:
        - name: mssql-storage
          persistentVolumeClaim:
            claimName: mssql-pvc
