apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-persistence
  labels:
    app: contact-api
    service: persistence
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contact-persistence
  template:
    metadata:
      labels:
        app: contact-persistence
    spec:
      containers:
        - name: contact-persistence
          image: gricardo10/contact-persistence:1.0.0
          env:
            - name: ConnectionStrings__Database
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: connectionString
            - name: MessageBroker__Host
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: messageBrokerHost
          # readinessProbe:
          #   exec:
          #     command:
          #       - /bin/bash
          #       - -c
          #       - |
          #         /opt/mssql-tools18/bin/sqlcmd -S mssql-svc -U sa -P P@ssw0rd1 -Q "SELECT 1" -C
          #   initialDelaySeconds: 20
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   failureThreshold: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      initContainers:
      - name: wait-for-rabbit
        image: busybox
        command: ['sh', '-c', 'until nc -z rabbitmq-svc 5672; do echo waiting for rabbitmq; sleep 5; done']

      - name: wait-for-mssql
        image: busybox
        command: ['sh', '-c', 'until nc -z mssql-svc 1433; do echo waiting for mssql; sleep 5; done']
